### ISSUE TITLE
Result Plots and Tables

### ISSUE THREAD

**Issue by stavrosgreece** [stavrosgreece/PoweFlowNet#17]
Revamp the plots of the paper.

Since we generate Datasetv3 and need to rerun experiments we can also add results for more cases (need to discuss this).  Cases between 118 and 6470 might be of interest (the greater the number of nodes the better our architecture look).

We show transferability is not great with our architecture, but what if we did not train for 1000 epochs (->overfit) and try to find a way to make it more generalizable : 
1. Do few-shot training on the new grid case
2. Less initial training epochs

###Tasks
- [ ] Create new **script** for Error Per Feature Distribution Plots 
- [ ] Revamp the **Interpretability plots** to make the text visible
- [ ] Find the exact error of the DC Power Flow method
